# My aliases
alias gotonvim='cd ~/.config/nvim'
alias nvimconf='(cd ~/.config/nvim && nvim .)'
alias vim='nvim'
alias v='nvim'
alias cls='clear'
alias gs='git status'
alias gfetch='git fetch'
alias ga='git add .'
alias gpull='git pull'
alias gpush='git push'
alias ls='ls --color=auto'
alias ll='ls -la --color=auto'
alias grep='grep --color=auto'
alias cls='clear'
